### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[60,1200]

### ISSUE THREAD

**Issue by coldmanck** [unilight/R-NET-in-Tensorflow#1]
Hi @unilight 

Thanks for your wonderful reproduction of R-Net. I encountered this error below:
```
W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[60,1200]
```
 In your readme you mentioned there are [some solution to this OOM problem](https://github.com/unilight/R-NET-in-Tensorflow#oom). May you elaborate the third solution, which you mentioned 
> To achieve this one might have to hack into `Models/models_rnet`.

How to do it? Thanks :)

**Comment by unilight** [comment]
Hi coldmanck, 

Thank you for your attention on my work! Several followers have also asked me question regarding character embeddings recently. I'm working on it right now, making the program more user-friendly, so one can use a flag to determine whether to use char embedding or not. I'm also working on some bug fixes. I'll try to commit a new version ASAP!

**Comment by unilight** [comment]
Hi coldmanck,

I have put on a new version. Check it out and let me know if it works!
