### ISSUE TITLE
Need to add __init__.py to Models Package

### ISSUE THREAD

**Issue by roozbehataisera** [unilight/R-NET-in-Tensorflow#2]
Otherwise you get

```
Traceback (most recent call last):
  File "rnet.py", line 2, in <module>
    from Models import model_rnet
ImportError: No module named Models
```

**Comment by bobycv06fpm** [comment]
hi Unilight,
I tried running your code.
I donot get the results you quoted.I followed the instructions. 
I get {"exact_match": 1.0406811731315042, "f1": 2.5807290442852833}
Any guess on why the aberration?
The results you quoted are put below.
Model | Dev EM Score | Dev F1 Score
-- | -- | --
Original Paper | 71.1 | 79.5
My (Adadelta, 2 layer, dropouts, w/o char emb) | 62.6 | 71.5
My (Adadelta, 1 layer, dropouts, w/o char emb) | 61.0 | 70.3
My (Adam, 1 layer, dropouts, w/o char emb) | 60.8 | 70.5
My (Adam, 1 layer, w/o char emb) | 57.8 | 67.9
My (Adam, 1 layer, w/ char emb) | 60.1 | 68.9

**Comment by unilight** [comment]
I've tested without the `__init__.py` file and it worked fine. Also, I've released a set of trained weight parameters. So I'm closing this.
