### ISSUE TITLE
Can we do transfer learning on R-net?

### ISSUE THREAD

**Issue by jenniferzhu** [unilight/R-NET-in-Tensorflow#6]
i.e. how can we add new paragraphs for R-net to generate answer from in real practice? Thanks

**Comment by unilight** [comment]
Hi @jenniferzhu ,
I'm not sure if my interpretation of "**transfer learning**" is the same as yours. R-Net is a model designed for Machine Reading Comprehension (MRC), so "_Transfer learning on R-net_" to me is to use model parameters obtained by training R-Net on some large dataset (SQuAD, for instance) to help solve another ML or NLP task better. It is definitely possible.
You mentioned "_add new paragraphs for R-net to generate answer from_", which differs from my interpretation of transfer learning, but at the same time, is also possible. You can either add new paragraphs along with some QA pairs to enlarge the training set, or simply test R-Net on paragraphs and QA pairs it has not seen.
Hope this helps! :)

**Comment by jenniferzhu** [comment]
@unilight Thanks for your response! You basically mentioned two options I was hoping for. Can you explain more on how to "simply test R-Net on paragraphs and QA pairs it has not seen"?

**Comment by unilight** [comment]
First you need to have a set of new paragraphs. `preprocess.py` provides details for how to perform tokenizing and other necessary preprocessing on the new paragraphs. Then one can test a trained R-Net model on the paragraphs.

**Comment by unilight** [comment]
Closing this issue.
