### ISSUE TITLE
the result is not good by default setting

### ISSUE THREAD

**Issue by andyyuan78** [unilight/R-NET-in-Tensorflow#9]
11 epoch 1434 batch, Loss:213.51, Acc:0.35
11 epoch 1435 batch, Loss:264.95, Acc:0.37
11 epoch 1436 batch, Loss:293.33, Acc:0.27
11 epoch 1437 batch, Loss:219.04, Acc:0.35
11 epoch 1438 batch, Loss:232.19, Acc:0.42
11 epoch 1439 batch, Loss:199.04, Acc:0.47
11 epoch 1440 batch, Loss:228.41, Acc:0.32
11 epoch 1441 batch, Loss:283.48, Acc:0.30
11 epoch 1442 batch, Loss:183.52, Acc:0.50
11 epoch 1443 batch, Loss:390.74, Acc:0.25
11 epoch 1444 batch, Loss:155.02, Acc:0.53
11 epoch 1445 batch, Loss:168.39, Acc:0.53
11 epoch 1446 batch, Loss:275.70, Acc:0.27
11 epoch 1447 batch, Loss:185.64, Acc:0.50
11 epoch 1448 batch, Loss:207.22, Acc:0.37
11 epoch 1449 batch, Loss:292.28, Acc:0.30
11 epoch 1450 batch, Loss:244.72, Acc:0.25
11 epoch 1451 batch, Loss:214.99, Acc:0.43
11 epoch 1452 batch, Loss:194.86, Acc:0.30
11 epoch 1453 batch, Loss:285.40, Acc:0.35
11 epoch 1454 batch, Loss:225.28, Acc:0.43
11 epoch 1455 batch, Loss:206.02, Acc:0.38
11 epoch 1456 batch, Loss:194.24, Acc:0.47
---------------
save path: Models/save/rnet_model_final.ckpt
gpuws@gpuws32g:~/ub16_prj/R-NET-in-Tensorflow$

**Comment by unilight** [comment]
Hi @andyyuan78 

Could you test the model with the evaluation data? So we can better analyze your results.

Thanks!

**Comment by unilight** [comment]
Closing this.
